### PR TITLE
use PicoSAT_jll artifact

### LINKED ISSUE #17: use Artifacts

### PR DESCRIPTION
**Pull request by CarloLucibello**
The artifact was introduced here
https://github.com/JuliaPackaging/Yggdrasil/pull/4061

Fix #17

### CODE REVIEW

**Comment by CarloLucibello** [comment]
@Wimmerer do you have any clue why this is failing on windows?

**Comment by rayegun** [comment]
I couldn't get it to build on Windows, so there's no jll for Windows

**Comment by CarloLucibello** [comment]
This is a pity. I wish there was a way to force windows users to stay on old versions of this package then.

**Comment by rayegun** [comment]
I can try to take a look at the PicoSAT builder again, but I'm pretty behind on other work as is (as you know 😅).

I have a couple other SAT solvers to build also. There are some that do build for Windows. My goal was eventually to have a uniform interface for all of them, that way if you needed a Windows one you just swapped out a constructor.

**Comment by CarloLucibello** [comment]
@MaximeBouton would you be ok with merging this and therefore dropping support for windows on v0.4.0?
The current version doesn't build on some architectures in any case (e.g. on my mac with M1 pro)

**Pull request merged**
